//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class db_testsEntities_server4 : DbContext
{
    public db_testsEntities_server4()
        : base("name=db_testsEntities_server4")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<server4_table_tests> server4_table_tests { get; set; }
    public virtual DbSet<view_table_tests> view_table_tests { get; set; }
}
